# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KakaoTalk-Clone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KakaoTalk-Clone
  pod 'Alamofire', '~> 5.2'

  target 'KakaoTalk-CloneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KakaoTalk-CloneUITests' do
    # Pods for testing
  end

end
